version: '3.2'
services:
  app:
    restart: unless-stopped
    image: mosystems/dolibarr:10.0.3-debug
    environment:
      - DOLIBARR_SETUP_LANG=en_US
      - DOLIBARR_MAIN_URL=http://dolibarr.example.com
      - DOLIBARR_DB_HOST=db
      - DOLIBARR_DB_NAME=dolibarr
      - DOLIBARR_DB_USER=dolibarr
      - DOLIBARR_DB_PASS=dbpassword
      - DOLIBARR_DB_PORT=3306
      - DOLIBARR_FORCE_HTTPS=0
      - DOLIBARR_AUTH=dolibarr
      - DOLIBARR_ADMIN_USER=admin
      - DOLIBARR_ADMIN_PASS=admin
    volumes:
      - www:/www
      - documents:/documents
      - sessions:/sessions
    depends_on: 
      - db
  
  web:
    image: nginx:stable
    volumes:
      - www:/www
    ports: 
      - 8080:80
    command: /bin/bash -c "curl -L 'https://git.io/JeMV0' -o /etc/nginx/conf.d/default.conf && nginx -d 'daemon off;'"
    depends_on: 
      - app

  db:
    image: mariadb:10.4
    environment:
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - database:/var/lib/mysql
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci'
    ]

volumes:
  www:
  database:
  documents:
  sessions: