version: '3.2'
services:
  app:
    restart: unless-stopped
    image: mosystems/dolibarr:latest
    environment:
      - DOLIBARR_SETUP_LANG=en_US
      - DOLIBARR_MAIN_URL=http://dolibarr.example.com
      - DOLIBARR_DB_HOST=db
      - DOLIBARR_DB_NAME=dolibarr
      - DOLIBARR_DB_USER=dolibarr
      - DOLIBARR_DB_PASS=dbpassword
      - DOLIBARR_DB_PORT=3306
      - DOLIBARR_FORCE_HTTPS=0
      - DOLIBARR_AUTH=dolibarr
      - DOLIBARR_ADMIN_USER=admin
      - DOLIBARR_ADMIN_PASS=admin
    volumes:
      - www:/www
      - documents:/documents
      - sessions:/sessions
    depends_on: 
      - db
  
  web:
    restart: unless-stopped
    image: nginx:stable
    volumes:
      - www:/www
      - nginx:/etc/nginx/conf.d
    ports: 
      - 8080:80
    depends_on: 
      - app
      - wget

  wget:
    image: busybox
    deploy:
      restart_policy:
        condition: on-failure
    command: wget -O /nginx/default.conf 'https://github.com/MOSystems/docker-dolibarr/raw/master/nginx.conf'
    volumes:
      - nginx:/nginx

  db:
    image: mariadb:10.4
    environment:
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - database:/var/lib/mysql
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci'
    ]

volumes:
  www:
  database:
  documents:
  sessions:
  nginx: