#!/bin/bash -x
tags=("${DOLIBARR_VERSION%%.*}" "${DOLIBARR_VERSION%.*}" "$DOLIBARR_VERSION")
for tag in $tags; do
    if [ "$DOCKER_TAG" = "debug" ]; then
        tag="${tag}-debug"
    fi
    docker tag "$IMAGE_NAME" "$DOCKER_REPO:$tag"
    docker push "$DOCKER_REPO:$tag"
done